const titleEl=document.getElementById('title'),tracksEl=document.getElementById('tracks'),preparedEl=document.getElementById('prepared'),statusEl=document.getElementById('status'),errorEl=document.getElementById('error'),prepareBtn=document.getElementById('prepare');
let activeTabId=null,currentInfo=null,preparedItems=[];
const showError=m=>errorEl.textContent=m||'发生未知错误。',clearError=()=>errorEl.textContent='',showStatus=m=>{statusEl.style.display='block';statusEl.textContent=m;},clearStatus=()=>{statusEl.style.display='none';statusEl.textContent='';};
async function getActiveTab(){const [tab]=await chrome.tabs.query({active:true,currentWindow:true});if(!tab?.id)throw new Error('无法读取当前标签页。');return tab;}
function formatBytes(n){if(!Number.isFinite(n))return '';if(n<1024)return `${n} B`;if(n<1048576)return `${(n/1024).toFixed(1)} KB`;return `${(n/1048576).toFixed(1)} MB`;}
function renderTracks(info){titleEl.textContent=info.title;tracksEl.innerHTML='';info.tracks.forEach(track=>{const label=document.createElement('label');label.className='track';const cb=document.createElement('input');cb.type='checkbox';cb.value=track.language;cb.checked=false;const body=document.createElement('div'),name=document.createElement('div');name.className='label';name.textContent=track.label;if(track.ai){const ai=document.createElement('span');ai.className='ai';ai.textContent=track.ai;name.appendChild(ai);}if(preparedItems.some(x=>x.language===track.language)){const done=document.createElement('span');done.className='generated';done.textContent='✓ 已生成';name.appendChild(done);}const meta=document.createElement('div');meta.className='meta';meta.textContent=track.language;body.append(name,meta);label.append(cb,body);tracksEl.appendChild(label);});prepareBtn.disabled=false;}
async function send(type,payload={}){const r=await chrome.tabs.sendMessage(activeTabId,{type,...payload});if(!r?.ok)throw new Error(r?.error||'操作失败。');return r;}
function selectedPrepared(){return [...preparedEl.querySelectorAll('.prepared-check:checked')].map(x=>x.value);}
function updateBatchButtons(){const n=selectedPrepared().length,save=document.getElementById('save-selected'),del=document.getElementById('delete-selected');if(save){save.disabled=!n;save.textContent=n?`保存选中（${n}）`:'保存选中';}if(del){del.disabled=!n;del.textContent=n?`删除选中（${n}）`:'删除选中';}}
function renderPrepared(items){preparedItems=items||[];preparedEl.innerHTML='';if(!preparedItems.length){preparedEl.innerHTML='<div class="empty">尚未生成字幕资源。</div>';if(currentInfo)renderTracks(currentInfo);return;}
const head=document.createElement('div');head.className='section-head';head.innerHTML='<div class="section-title">已准备好的字幕</div>';const clear=document.createElement('button');clear.className='clear-link';clear.textContent='清空全部';head.appendChild(clear);preparedEl.appendChild(head);
const hint=document.createElement('div');hint.className='cache-hint';hint.innerHTML='<strong>临时缓存</strong><br>已生成字幕暂存在当前视频标签页中。刷新页面、关闭该标签页、关闭浏览器，或切换到其他 Mnet Plus 视频后，缓存将被清除。请及时保存需要的字幕。';preparedEl.appendChild(hint);
preparedItems.forEach(item=>{const row=document.createElement('div');row.className='prepared-item';const cb=document.createElement('input');cb.type='checkbox';cb.className='prepared-check';cb.value=item.language;cb.onchange=updateBatchButtons;const body=document.createElement('div');body.className='prepared-body';const name=document.createElement('div');name.className='label';name.textContent=`${item.label||item.language} · ${item.count} 条${item.size?` · ${formatBytes(item.size)}`:''}`;const meta=document.createElement('div');meta.className='meta filename';meta.textContent=item.filename;const save=document.createElement('button');save.className='save-one';save.textContent='保存';save.onclick=async()=>{clearError();save.disabled=true;try{await send('MNET_SUB_SAVE_PREPARED',{languages:[item.language]});showStatus(`已发起保存：${item.filename}\n如果在系统保存窗口点了“取消”，资源仍保留，可再次保存。`);}catch(e){showError(e.message);}finally{save.disabled=false;}};body.append(name,meta);row.append(cb,body,save);preparedEl.appendChild(row);});
const batch=document.createElement('div');batch.className='batch';const saveSelected=document.createElement('button');saveSelected.id='save-selected';saveSelected.disabled=true;saveSelected.textContent='保存选中';saveSelected.onclick=async()=>{const languages=selectedPrepared();if(!languages.length)return;try{clearError();await send('MNET_SUB_SAVE_PREPARED',{languages});showStatus(`已发起 ${languages.length} 个字幕的保存。取消任一系统保存窗口不会删除临时资源。`);}catch(e){showError(e.message);}};const deleteSelected=document.createElement('button');deleteSelected.id='delete-selected';deleteSelected.className='danger';deleteSelected.disabled=true;deleteSelected.textContent='删除选中';deleteSelected.onclick=async()=>{const languages=selectedPrepared();if(!languages.length)return;try{clearError();const r=await send('MNET_SUB_DELETE_PREPARED',{languages});renderPrepared(r.prepared);showStatus(`已从临时缓存删除 ${languages.length} 个字幕。`);}catch(e){showError(e.message);}};batch.append(saveSelected,deleteSelected);preparedEl.appendChild(batch);
clear.onclick=()=>{if(document.getElementById('clear-confirm'))return;const box=document.createElement('div');box.id='clear-confirm';box.className='confirm';box.innerHTML=`确定清空全部 ${preparedItems.length} 个已生成字幕吗？<br>清空后需要重新生成。`;const actions=document.createElement('div');actions.className='confirm-actions';const cancel=document.createElement('button');cancel.className='secondary';cancel.textContent='取消';cancel.onclick=()=>box.remove();const yes=document.createElement('button');yes.className='danger';yes.textContent='确认清空';yes.onclick=async()=>{try{const r=await send('MNET_SUB_CLEAR_PREPARED');renderPrepared(r.prepared);showStatus('临时字幕缓存已清空。');}catch(e){showError(e.message);}};actions.append(cancel,yes);box.appendChild(actions);head.after(box);};if(currentInfo)renderTracks(currentInfo);}
chrome.runtime.onMessage.addListener(message=>{if(message?.type==='MNET_SUB_PROGRESS')showStatus(`正在生成 ${message.language}…\n${message.done}/${message.total} 秒 · 已收集 ${message.count} 条字幕`);});
(async()=>{try{const tab=await getActiveTab();activeTabId=tab.id;if(!tab.url?.includes('mnetplus.world/media/')||!tab.url.includes('/videos/'))throw new Error('请先打开一个 Mnet Plus 视频页面，再点击扩展。');const r=await send('MNET_SUB_GET_INFO');currentInfo=r.info;preparedItems=r.prepared||[];renderTracks(currentInfo);renderPrepared(preparedItems);}catch(e){titleEl.textContent='无法识别当前页面';showError(e.message);prepareBtn.disabled=true;}})();
prepareBtn.addEventListener('click',async()=>{const languages=[...document.querySelectorAll('#tracks input[type="checkbox"]:checked')].map(x=>x.value);if(!languages.length){showError('请至少选择一种字幕。');return;}const replacing=languages.filter(l=>preparedItems.some(x=>x.language===l));clearError();prepareBtn.disabled=true;showStatus(replacing.length?`正在生成：${languages.join(', ')}\n其中 ${replacing.join(', ')} 已有缓存，将重新生成并替换。`:`正在生成：${languages.join(', ')}`);try{const r=await send('MNET_SUB_PREPARE',{languages});renderPrepared(r.prepared||[]);showStatus('生成完成。字幕已放入下方临时资源区，可单独保存或多选操作。');}catch(e){showError(e.message);showStatus('字幕生成未完成。');}finally{prepareBtn.disabled=false;}});
